DROP DATABASE IF EXISTS academia;
CREATE DATABASE academia;
USE academia;

CREATE TABLE alunos(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  nascto DATE NOT NULL,
  sexo VARCHAR(255) NOT NULL,
  peso VARCHAR(255) NOT NULL
);

CREATE TABLE telefones(
  idaluno INT NOT NULL AUTO_INCREMENT,
  telefone VARCHAR(255) NOT NULL,
  FOREIGN KEY (idaluno) REFERENCES alunos(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE exercicios(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  grupo_muscular VARCHAR(255) NOT NULL,
  aparelho VARCHAR(255) NOT NULL
);

CREATE TABLE ficha(
  idaluno INT NOT NULL,
  idexercicio INT NOT NULL,
  dia_semana VARCHAR(255) NOT NULL,
  serie VARCHAR(255) NOT NULL,
  FOREIGN KEY (idaluno) REFERENCES alunos(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (idexercicio) REFERENCES exercicios(id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO alunos VALUES
(null,"Gustavo","2003-10-18","M","140");

INSERT INTO telefones VALUES
(1,"19982618248");

INSERT INTO exercicios VALUES
(null,"Supino reto","Peito","prancha peito reto");

INSERT INTO ficha VALUES
(1,1,"segunda","4R decrescente 12 10 8 6");
