DROP DATABASE IF EXISTS clientes;

CREATE DATABASE clientes;

USE clientes;

CREATE TABLE
  clientes (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    nascto DATE NOT NULL,
    sexo VARCHAR(255) NOT NULL,
    peso VARCHAR(255) NOT NULL
  );

CREATE TABLE
  telefones (
    idcliente INT NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    FOREIGN KEY (idcliente) REFERENCES clientes (id) ON DELETE CASCADE ON UPDATE CASCADE
  );

LOAD DATA INFILE 'E:/Gustavo/BCD/Aula004/exercicios/ex001/clientes.csv' INTO TABLE clientes FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE 'E:/Gustavo/BCD/Aula004/exercicios/ex001/telefone.csv' INTO TABLE telefones FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;